# 全局配置
global:
  max_replies: 3
  rules_file: "rules.csv"
  default_reply: "自动回复机器人出故障了www，请联系我的master修一下QwQ"
  reset_interval: 60  # 重置间隔（分钟）
  my_wx_name: "John Teller"

# 监听的联系人列表
contacts:
  - name: "John Teller"
    enabled: true  # 是否启用
    prefix: "我是自动回复机器人张和，我的主人现在失踪了，我先代为回复~"  # 可选，自定义前缀消息
  - name: "姚力眉"
    enabled: false # 以通过设置enabled来控制是否监听该联系人